# Generated by Django 5.2.3 on 2025-07-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_create_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="role",
            field=models.CharField(
                choices=[("ADMINISTRATOR", "ADMINISTRATOR"), ("USER", "USER")],
                default="USER",
                max_length=32,
            ),
        ),
    ]
