# Generated by Django 5.2.3 on 2025-07-04 12:58

from django.db import migrations, models

import authentication.models.user_profile


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_update_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="password_reset_token_expires_at",
            field=models.DateTimeField(
                blank=True,
                default=authentication.models.user_profile.default_token_expiration,
                null=True,
            ),
        ),
    ]
