# Generated by Django 5.2.3 on 2025-07-05 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_add_new_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="client",
            field=models.ForeignKey(
                default="ffb268c3-7923-4361-a2d6-318a0ef6bcf3",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="authentication.clients",
            ),
            preserve_default=False,
        ),
    ]
