# Generated by Django 5.2.3 on 2025-07-05 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_fix_updated_at_behavior"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boards",
            name="project_id",
        ),
        migrations.AddField(
            model_name="boards",
            name="project",
            field=models.ForeignKey(
                default="b1f7a9eb-6353-418d-9455-f0beec139515",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="authentication.projects",
            ),
            preserve_default=False,
        ),
    ]
