# Generated by Django 5.2.3 on 2025-08-24 01:31

import datetime
import uuid

import django.db.models.deletion
from django.db import migrations, models

# import authentication.models.users


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_add_project_fk_to_boards"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("full_name", models.CharField(max_length=120, verbose_name="name")),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMINISTRATOR", "ADMINISTRATOR"), ("USER", "USER")],
                        default="USER",
                        max_length=20,
                    ),
                ),
                ("job_title", models.CharField(max_length=80)),
                ("department", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=8,
                    ),
                ),
                ("joined_at", models.DateField(default=datetime.date.today)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="authentication.clients",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(fields=["full_name"], name="users_full_na_0edea9_idx"),
                    models.Index(fields=["department"], name="users_departm_d50da8_idx"),
                    models.Index(fields=["status"], name="users_status_9ca66f_idx"),
                    models.Index(fields=["email"], name="users_email_4b85f2_idx"),
                ],
            },
        ),
    ]
