# Generated by Django 5.2.3 on 2025-09-08 18:15

import uuid

from django.db import migrations, models

import authentication.models.agents


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_add_user_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agents",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=authentication.models.agents.avatar_upload_to,
                    ),
                ),
                ("url_n8n", models.URLField()),
            ],
            options={
                "verbose_name": "Bot",
                "verbose_name_plural": "Agents",
                "db_table": "agents",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="agents_name_71fde0_idx")],
            },
        ),
    ]
