# Generated by Django 5.2.3 on 2025-09-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_add_bots"),
    ]

    operations = [
        migrations.AddField(
            model_name="boards",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="agents",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clients",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="invite",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="projects",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userinvites",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="users",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
