# Generated by Django 5.2.3 on 2025-09-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_update_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="agents",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="authentication.agents"
            ),
        ),
    ]
