# Generated by Django 5.2.3 on 2025-09-10 11:37

import uuid

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_add_bots_m2m_to_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertiseArea",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Expertise Area",
                "verbose_name_plural": "Expertise Areas",
                "db_table": "expertise_areas",
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="expertise_a_name_a7f12b_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="uq_expertisearea_name_ci",
                        violation_error_message="An expertise area with this name already exists.",
                    )
                ],
            },
        ),
    ]
