# Generated by Django 5.2.3 on 2025-09-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_add_expertise_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="agents",
            name="expertise_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bots",
                to="authentication.expertisearea",
            ),
        ),
    ]
