# Generated by Django 5.2.3 on 2025-09-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_expertise_area_to_bots"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="authentication.users"
            ),
        ),
    ]
