# Generated by Django 5.2.3 on 2025-09-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_add_user_project_m2m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boards",
            name="active",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="agents",
            name="active",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="active",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="expertisearea",
            name="active",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="invite",
            name="active",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="active",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="userinvites",
            name="active",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="active",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="active",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
