# Generated by Django 5.2.3 on 2025-09-13 05:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import authentication.models.user_profile


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_alter_boards_active_alter_bots_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=authentication.models.user_profile.avatar_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_profiles",
                to="authentication.clients",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(default="test", max_length=120, verbose_name="name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_title",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="joined_at",
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="boards",
            name="active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="agents",
            name="active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="clients",
            name="active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="expertisearea",
            name="active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="invite",
            name="active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userinvites",
            name="active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
