# Generated by Django 5.2.3 on 2025-10-09

import uuid

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0016_fix_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True, default=uuid.uuid4, serialize=False, editable=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True, blank=True)),
                ("active", models.BooleanField(null=True, default=True)),
                ("source_text", models.CharField(max_length=191, db_index=True)),
                ("target_lang", models.CharField(max_length=10)),
                ("translated_text", models.TextField()),
                ("namespace", models.CharField(max_length=64, blank=True, default="")),
            ],
            options={
                "db_table": "authentication_translation",
            },
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                fields=["source_text", "target_lang", "namespace"],
                name="uniq_source_lang_namespace",
            ),
        ),
        migrations.AddIndex(
            model_name="translation",
            index=models.Index(
                fields=["target_lang", "namespace"], name="translation_lang_ns_idx"
            ),
        ),
    ]
