# Generated by Django 5.2.3 on 2025-10-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_i18n_translation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="source_text",
            field=models.CharField(db_index=True, max_length=191),
        ),
    ]
