# Generated by Django 5.2.3 on 2025-10-09 22:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0019_alter_translation_source_text"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="translation",
            new_name="authenticat_target__bf0d4c_idx",
            old_name="translation_lang_ns_idx",
        ),
        migrations.AlterField(
            model_name="translation",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="translation",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterModelTable(
            name="translation",
            table=None,
        ),
    ]
