# Generated by Django 5.2.3 on 2025-10-17 19:19

import django.db.models.deletion
from django.db import migrations, models

AGENTS_TABLE = "authentication_agents"
BOARDS_TABLE = "authentication_boards"
CLIENTS_TABLE = "authentication_clients"
EXPERTISE_TABLE = "authentication_expertisearea"
INVITE_TABLE = "authentication_invite"
PROJECTS_TABLE = "authentication_projects"
TRANSL_TABLE = "authentication_translation"
USERINVITES_TABLE = "authentication_userinvites"
USERPROFILE_TABLE = "authentication_userprofile"

SQL_RENAME_INDEX_AGENTS = f"""
-- renomeia o índice antigo -> novo, só se tabela+índice existirem
SET @tbl := (SELECT COUNT(*) FROM information_schema.tables
             WHERE table_schema = DATABASE() AND table_name = '{AGENTS_TABLE}');
SET @idx := (SELECT COUNT(*) FROM information_schema.statistics
             WHERE table_schema = DATABASE() AND table_name = '{AGENTS_TABLE}'
               AND index_name = 'agents_name_71fde0_idx');
SET @stmt := IF(@tbl > 0 AND @idx > 0,
  'ALTER TABLE `{AGENTS_TABLE}` RENAME INDEX `agents_name_71fde0_idx` TO `agents_name_6f5710_idx`',
  'SELECT 1');
PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
"""


def sql_drop_column_if_exists(table, column):
    return f"""
SET @col := (
  SELECT COUNT(*) FROM information_schema.columns
  WHERE table_schema = DATABASE() AND table_name = '{table}' AND column_name = '{column}'
);
SET @stmt := IF(@col > 0, 'ALTER TABLE `{table}` DROP COLUMN `{column}`', 'SELECT 1');
PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
""".replace(
        "{table}", table
    ).replace(
        "{column}", column
    )


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0020_sync_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(SQL_RENAME_INDEX_AGENTS, reverse_sql=migrations.RunSQL.noop)
            ],
            state_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql_drop_column_if_exists(AGENTS_TABLE, "active")),
                migrations.RunSQL(sql_drop_column_if_exists(BOARDS_TABLE, "active")),
                migrations.RunSQL(sql_drop_column_if_exists(BOARDS_TABLE, "name")),
                migrations.RunSQL(sql_drop_column_if_exists(CLIENTS_TABLE, "active")),
                migrations.RunSQL(sql_drop_column_if_exists(EXPERTISE_TABLE, "active")),
                migrations.RunSQL(sql_drop_column_if_exists(INVITE_TABLE, "active")),
                migrations.RunSQL(sql_drop_column_if_exists(PROJECTS_TABLE, "active")),
                migrations.RunSQL(sql_drop_column_if_exists(TRANSL_TABLE, "active")),
                migrations.RunSQL(sql_drop_column_if_exists(USERINVITES_TABLE, "active")),
                migrations.RunSQL(sql_drop_column_if_exists(USERPROFILE_TABLE, "status")),
            ],
            state_operations=[
                migrations.RemoveField(model_name="agents", name="active"),
                migrations.RemoveField(model_name="boards", name="active"),
                migrations.RemoveField(model_name="boards", name="name"),
                migrations.RemoveField(model_name="clients", name="active"),
                migrations.RemoveField(model_name="expertisearea", name="active"),
                migrations.RemoveField(model_name="invite", name="active"),
                migrations.RemoveField(model_name="projects", name="active"),
                migrations.RemoveField(model_name="translation", name="active"),
                migrations.RemoveField(model_name="userinvites", name="active"),
                migrations.RemoveField(model_name="userprofile", name="status"),
            ],
        ),
        migrations.AlterModelOptions(
            name="agents",
            options={
                "ordering": ["name"],
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
            },
        ),
        migrations.AddField(
            model_name="invite",
            name="client",
            field=models.ForeignKey(
                default="312ad97ac3494d128fc7c4fa3fedc1e8",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invites",
                to="authentication.clients",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agents",
            name="expertise_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="authentication.expertisearea",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMINISTRATOR", "ADMINISTRATOR"),
                    ("MANAGER", "MANAGER"),
                    ("USER", "USER"),
                ],
                default="USER",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile", name="active", field=models.BooleanField(default=True)
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMINISTRATOR", "ADMINISTRATOR"),
                    ("MANAGER", "MANAGER"),
                    ("USER", "USER"),
                ],
                default="USER",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
