# Generated by Django 5.2.3 on 2025-10-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0022_refactor_db"),
    ]

    operations = [
        # Create the through table and indexes if they don't exist yet (DB ops),
        # and register the model + field changes in the migration state.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        """
                        CREATE TABLE IF NOT EXISTS `authentication_projects_bots` (
                          `id` bigint NOT NULL AUTO_INCREMENT,
                          `projects_id` char(32) NOT NULL,
                          `bots_id` char(32) NOT NULL,
                          PRIMARY KEY (`id`)
                        ) ENGINE=InnoDB;
                        """
                    ),
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ProjectsAgentsThrough",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "agent",
                            models.ForeignKey(
                                db_column="bots_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to="authentication.agents",
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                db_column="projects_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                to="authentication.projects",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "authentication_projects_bots",
                    },
                ),
                migrations.AlterField(
                    model_name="projects",
                    name="agents",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        through="authentication.ProjectsAgentsThrough",
                        through_fields=("project", "agent"),
                        to="authentication.agents",
                    ),
                ),
                migrations.AddIndex(
                    model_name="projectsagentsthrough",
                    index=models.Index(fields=["project"], name="authenticat_project_f20c07_idx"),
                ),
                migrations.AddIndex(
                    model_name="projectsagentsthrough",
                    index=models.Index(fields=["agent"], name="authenticat_bots_id_f2cf4d_idx"),
                ),
                migrations.AddConstraint(
                    model_name="projectsagentsthrough",
                    constraint=models.UniqueConstraint(
                        fields=("project", "agent"), name="uq_projects_agents"
                    ),
                ),
            ],
        ),
    ]
