# Generated by Django 5.2.3 on 2025-10-22 18:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0023_projectsagentsthrough_alter_projects_agents_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KBLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("external_id", models.CharField(db_index=True, max_length=128)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kb_links",
                        to="authentication.projects",
                    ),
                ),
            ],
            options={
                "db_table": "kb_links",
                "indexes": [
                    models.Index(fields=["project"], name="kb_links_project_10b278_idx"),
                    models.Index(fields=["external_id"], name="kb_links_externa_ad3117_idx"),
                ],
                "unique_together": {("project", "external_id")},
            },
        ),
    ]
