# Generated by Django 5.2.3 on 2025-10-28 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0025_fix_agents_expertise_area_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="boards",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="authentication.clients",
            ),
        ),
    ]
