# Generated by Django 5.2.3 on 2025-11-03

from django.db import migrations

SQL_FIX_THROUGH_FK = r"""

SET @fk := (
  SELECT CONSTRAINT_NAME
  FROM information_schema.KEY_COLUMN_USAGE
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'authentication_projects_bots'
    AND COLUMN_NAME = 'bots_id'
    AND REFERENCED_TABLE_NAME = 'bots'
  LIMIT 1
);
SET @stmt := IF(
  @fk IS NOT NULL,
  CONCAT('ALTER TABLE `authentication_projects_bots` DROP FOREIGN KEY `', @fk, '`'),
  'SELECT 1'
);
PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;

SET @col := (
  SELECT CHARACTER_MAXIMUM_LENGTH
  FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'authentication_projects_bots'
    AND COLUMN_NAME = 'bots_id'
);
SET @stmt := IF(
  @col IS NOT NULL AND @col <> 36,
  'ALTER TABLE `authentication_projects_bots` MODIFY `bots_id` CHAR(36) NOT NULL',
  'SELECT 1'
);
PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;

SET @fk_agents := (
  SELECT CONSTRAINT_NAME
  FROM information_schema.KEY_COLUMN_USAGE
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'authentication_projects_bots'
    AND COLUMN_NAME = 'bots_id'
    AND REFERENCED_TABLE_NAME = 'agents'
  LIMIT 1
);
SET @stmt := IF(
  @fk_agents IS NULL,
  'ALTER TABLE `authentication_projects_bots`\n   ADD CONSTRAINT `authentication_projects_bots_bots_id_fk_agents`\n   FOREIGN KEY (`bots_id`) REFERENCES `agents`(`id`)\n   ON DELETE CASCADE',
  'SELECT 1'
);
PREPARE s FROM @stmt; EXECUTE s; DEALLOCATE PREPARE s;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0028_fix_projects_bots_uuid_len"),
    ]

    operations = [
        migrations.RunSQL(SQL_FIX_THROUGH_FK, reverse_sql=migrations.RunSQL.noop),
    ]
