# Generated by Django 5.2.3 on 2025-11-03

from django.db import migrations

SQL_FIX_THROUGH_FK = r"""
    DO $$
    DECLARE fk_name text;
    BEGIN

        SELECT conname
        INTO fk_name
        FROM pg_constraint
        WHERE conrelid = 'authentication_projects_bots'::regclass
        AND contype = 'f'
        LIMIT 1;

        IF fk_name IS NOT NULL THEN
            EXECUTE format(
                'ALTER TABLE authentication_projects_bots DROP CONSTRAINT %I',
                fk_name
            );
        END IF;

        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name = 'authentication_projects_bots'
            AND column_name = 'bots_id'
            AND data_type <> 'uuid'
        ) THEN
            ALTER TABLE authentication_projects_bots
            ALTER COLUMN bots_id TYPE UUID
            USING bots_id::uuid;
        END IF;

        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'authentication_projects_bots_bots_id_fk_agents'
        ) THEN
            ALTER TABLE authentication_projects_bots
            ADD CONSTRAINT authentication_projects_bots_bots_id_fk_agents
            FOREIGN KEY (bots_id)
            REFERENCES agents(id)
            ON DELETE CASCADE;
        END IF;
    END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0028_fix_projects_bots_uuid_len"),
    ]

    operations = [
        migrations.RunSQL(SQL_FIX_THROUGH_FK, reverse_sql=migrations.RunSQL.noop),
    ]
