# Generated by Django 5.2.3 on 2025-11-06

from django.db import connection, migrations


def backfill_user_clients(apps, schema_editor):
    Clients = apps.get_model("authentication", "Clients")
    UserProfile = apps.get_model("authentication", "UserProfile")
    Projects = apps.get_model("authentication", "Projects")

    def get_default_client():
        # Se existir ao menos um cliente, reutiliza o primeiro; caso contrário, retorna None.
        total_clients = Clients.objects.count()
        if total_clients >= 1:
            return Clients.objects.first()
        return None

    # Apenas usuários não-admin devem possuir client; admins permanecem sem client
    for user in UserProfile.objects.filter(client__isnull=True).exclude(role="ADMINISTRATOR"):
        # Clientes distintos dos projetos do usuário
        client_ids = list(
            Projects.objects.filter(users__id=user.id)
            .values_list("client_id", flat=True)
            .distinct()
        )
        chosen_client = None
        if len(client_ids) == 1:
            chosen_client = client_ids[0]
        elif len(client_ids) == 0:
            _c = get_default_client()
            chosen_client = _c.id if _c else None
        else:
            # múltiplos clientes -> escolher determinístico e remover laços com outros clientes
            client_ids_sorted = sorted([cid for cid in client_ids if cid is not None])
            if client_ids_sorted:
                chosen_client = client_ids_sorted[0]
            else:
                _c = get_default_client()
                chosen_client = _c.id if _c else None
            # Remover vínculos M2M com projetos de outros clientes via ORM (independente do nome da tabela M2M)
            for project in user.projects.exclude(client_id=chosen_client).all():
                user.projects.remove(project)
        if chosen_client is not None:
            user.client_id = chosen_client
            user.save(update_fields=["client"])


def create_triggers_enforce_same_client(apps, schema_editor):
    with connection.cursor() as cursor:

        # check M2M table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = current_schema()
                AND table_name = 'authentication_projects_users'
            )
        """)
        (tbl_exists,) = cursor.fetchone()

        if not tbl_exists:
            return

        # detect correct user column
        user_cols = []

        for col in ("userprofile_id", "users_id"):
            cursor.execute("""
                SELECT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = current_schema()
                    AND table_name = 'authentication_projects_users'
                    AND column_name = %s
                )
            """, [col])

            (exists,) = cursor.fetchone()
            if exists:
                user_cols.append(col)

        for user_col in user_cols:

            func_name = f"fn_enforce_client_{user_col}"
            trigger_name_insert = f"trg_apu_bi_{user_col}"
            trigger_name_update = f"trg_apu_bu_{user_col}"

            cursor.execute(f"""
            CREATE OR REPLACE FUNCTION {func_name}()
            RETURNS trigger AS $$
            DECLARE
                v_proj_client uuid;
                v_user_client uuid;
                v_role text;
            BEGIN
                SELECT client_id
                INTO v_proj_client
                FROM authentication_projects
                WHERE id = NEW.projects_id;

                SELECT client_id, role
                INTO v_user_client, v_role
                FROM authentication_userprofile
                WHERE id = NEW.{user_col};

                IF v_role <> 'ADMINISTRATOR'
                   AND (v_proj_client IS NULL
                        OR v_user_client IS NULL
                        OR v_proj_client <> v_user_client)
                THEN
                    RAISE EXCEPTION
                    'Cross-client project/user association not allowed ({user_col})';
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """)

            # INSERT trigger
            cursor.execute(f"""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_trigger
                    WHERE tgname = '{trigger_name_insert}'
                ) THEN
                    CREATE TRIGGER {trigger_name_insert}
                    BEFORE INSERT ON authentication_projects_users
                    FOR EACH ROW
                    EXECUTE FUNCTION {func_name}();
                END IF;
            END$$;
            """)

            # UPDATE trigger
            cursor.execute(f"""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_trigger
                    WHERE tgname = '{trigger_name_update}'
                ) THEN
                    CREATE TRIGGER {trigger_name_update}
                    BEFORE UPDATE ON authentication_projects_users
                    FOR EACH ROW
                    EXECUTE FUNCTION {func_name}();
                END IF;
            END$$;
            """)


def drop_triggers_enforce_same_client(apps, schema_editor):
    with connection.cursor() as cursor:

        for col in ("userprofile_id", "users_id"):

            cursor.execute(f"""
                DROP TRIGGER IF EXISTS trg_apu_bi_{col}
                ON authentication_projects_users
            """)

            cursor.execute(f"""
                DROP TRIGGER IF EXISTS trg_apu_bu_{col}
                ON authentication_projects_users
            """)

            cursor.execute(f"""
                DROP FUNCTION IF EXISTS fn_enforce_client_{col}()
            """)


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0029_fix_projects_bots_fk"),
    ]

    operations = [
        migrations.RunPython(backfill_user_clients, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(
            create_triggers_enforce_same_client, reverse_code=drop_triggers_enforce_same_client
        ),
    ]
