# Generated by Django 5.2.3 on 2025-11-06

from django.db import connection, migrations


def backfill_user_clients(apps, schema_editor):
    Clients = apps.get_model("authentication", "Clients")
    UserProfile = apps.get_model("authentication", "UserProfile")
    Projects = apps.get_model("authentication", "Projects")

    def get_default_client():
        # Se existir ao menos um cliente, reutiliza o primeiro; caso contrário, retorna None.
        total_clients = Clients.objects.count()
        if total_clients >= 1:
            return Clients.objects.first()
        return None

    # Apenas usuários não-admin devem possuir client; admins permanecem sem client
    for user in UserProfile.objects.filter(client__isnull=True).exclude(role="ADMINISTRATOR"):
        # Clientes distintos dos projetos do usuário
        client_ids = list(
            Projects.objects.filter(users__id=user.id)
            .values_list("client_id", flat=True)
            .distinct()
        )
        chosen_client = None
        if len(client_ids) == 1:
            chosen_client = client_ids[0]
        elif len(client_ids) == 0:
            _c = get_default_client()
            chosen_client = _c.id if _c else None
        else:
            # múltiplos clientes -> escolher determinístico e remover laços com outros clientes
            client_ids_sorted = sorted([cid for cid in client_ids if cid is not None])
            if client_ids_sorted:
                chosen_client = client_ids_sorted[0]
            else:
                _c = get_default_client()
                chosen_client = _c.id if _c else None
            # Remover vínculos M2M com projetos de outros clientes via ORM (independente do nome da tabela M2M)
            for project in user.projects.exclude(client_id=chosen_client).all():
                user.projects.remove(project)
        if chosen_client is not None:
            user.client_id = chosen_client
            user.save(update_fields=["client"])


def create_triggers_enforce_same_client(apps, schema_editor):
    # Enforce: para não-admins, project.client_id == user.client_id
    with connection.cursor() as cursor:
        # Verifica existência de tabela M2M
        cursor.execute(
            """
            SELECT COUNT(*) FROM information_schema.tables
            WHERE table_schema = DATABASE() AND table_name = 'authentication_projects_users'
            """
        )
        (tbl_exists,) = cursor.fetchone()
        if not tbl_exists:
            return

        # Descobre qual coluna de user existe (userprofile_id ou users_id)
        user_cols = []
        for col in ("userprofile_id", "users_id"):
            cursor.execute(
                """
                SELECT COUNT(*) FROM information_schema.columns
                WHERE table_schema = DATABASE()
                  AND table_name = 'authentication_projects_users'
                  AND column_name = %s
                """,
                [col],
            )
            (cnt,) = cursor.fetchone()
            if cnt:
                user_cols.append(col)

        def trigger_exists(name: str) -> bool:
            cursor.execute(
                """
                SELECT COUNT(*) FROM information_schema.triggers
                WHERE trigger_schema = DATABASE() AND trigger_name = %s
                """,
                [name],
            )
            (c,) = cursor.fetchone()
            return bool(c)

        def create_triggers_for_user_col(user_col: str):
            # BEFORE INSERT
            trg_bi = (
                "trg_apu_bi_enforce_client_userprofile"
                if user_col == "userprofile_id"
                else "trg_apu_bi_enforce_client_users"
            )
            if not trigger_exists(trg_bi):
                cursor.execute(
                    f"""
                    CREATE TRIGGER `{trg_bi}` BEFORE INSERT ON `authentication_projects_users`
                    FOR EACH ROW BEGIN
                      DECLARE v_proj_client CHAR(36);
                      DECLARE v_user_client CHAR(36);
                      DECLARE v_role VARCHAR(32);
                      SELECT `client_id` INTO v_proj_client FROM `authentication_projects` WHERE `id` = NEW.`projects_id`;
                      SELECT `client_id`, `role` INTO v_user_client, v_role FROM `authentication_userprofile` WHERE `id` = NEW.`{user_col}`;
                      IF v_role <> 'ADMINISTRATOR' AND (v_proj_client IS NULL OR v_user_client IS NULL OR v_proj_client <> v_user_client) THEN
                        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cross-client project/user association not allowed ({user_col} variant)';
                      END IF;
                    END
                    """
                )

            # BEFORE UPDATE
            trg_bu = (
                "trg_apu_bu_enforce_client_userprofile"
                if user_col == "userprofile_id"
                else "trg_apu_bu_enforce_client_users"
            )
            if not trigger_exists(trg_bu):
                cursor.execute(
                    f"""
                    CREATE TRIGGER `{trg_bu}` BEFORE UPDATE ON `authentication_projects_users`
                    FOR EACH ROW BEGIN
                      DECLARE v_proj_client CHAR(36);
                      DECLARE v_user_client CHAR(36);
                      DECLARE v_role VARCHAR(32);
                      SELECT `client_id` INTO v_proj_client FROM `authentication_projects` WHERE `id` = NEW.`projects_id`;
                      SELECT `client_id`, `role` INTO v_user_client, v_role FROM `authentication_userprofile` WHERE `id` = NEW.`{user_col}`;
                      IF v_role <> 'ADMINISTRATOR' AND (v_proj_client IS NULL OR v_user_client IS NULL OR v_proj_client <> v_user_client) THEN
                        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Cross-client project/user association not allowed ({user_col} variant)';
                      END IF;
                    END
                    """
                )

        for col in user_cols:
            create_triggers_for_user_col(col)


def drop_triggers_enforce_same_client(apps, schema_editor):
    with connection.cursor() as cursor:
        # Usar IF EXISTS para evitar erros
        cursor.execute("DROP TRIGGER IF EXISTS `trg_apu_bi_enforce_client_userprofile`")
        cursor.execute("DROP TRIGGER IF EXISTS `trg_apu_bu_enforce_client_userprofile`")
        cursor.execute("DROP TRIGGER IF EXISTS `trg_apu_bi_enforce_client_users`")
        cursor.execute("DROP TRIGGER IF EXISTS `trg_apu_bu_enforce_client_users`")


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0029_fix_projects_bots_fk"),
    ]

    operations = [
        migrations.RunPython(backfill_user_clients, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(
            create_triggers_enforce_same_client, reverse_code=drop_triggers_enforce_same_client
        ),
    ]
