# Generated by Django 5.2.3 on 2025-11-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0030_add_chat_sessions"),
        ("authentication", "0030_enforce_client_scope"),
    ]

    operations = []
