# Generated by Django 5.2.3 on 2025-11-11 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0031_merge_20251110_0942"),
        ("authentication", "0031_merge_20251110_1325"),
    ]

    operations = []
