# Generated by Django 5.2.3 on 2025-11-14 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0032_merge_20251111_1537"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message_id", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="kblink",
            name="kb_links_project_10b278_idx",
        ),
        migrations.RemoveIndex(
            model_name="kblink",
            name="kb_links_externa_ad3117_idx",
        ),
        migrations.RenameIndex(
            model_name="agents",
            new_name="agents_name_6f5710_idx",
            old_name="agents_name_71fde0_idx",
        ),
    ]