# Generated by Django 5.2.3 on 2025-11-06 20:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0033_add_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatfavorite",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_favorites",
                to="authentication.agents",
            ),
        ),
        migrations.AddField(
            model_name="chatfavorite",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="authentication.chatsession",
            ),
        ),
        migrations.AddField(
            model_name="chatfavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatfavorite",
            unique_together={("user", "agent", "session", "message_id")},
        ),
    ]
